"""M3 type-scale roles.

The figures come from Google's autogenerated token source (material-web,
Material 3 version 34.0.21), not from the spec page -- which serves a
JavaScript shell with no extractable table, and is why the copy in
`M3-References` is empty.

The tests below pin the sourcing as much as the behaviour: the scale must agree
with the four values the reference library corroborates independently, and must
settle the one it contradicts itself on.
"""

from __future__ import annotations

from itertools import pairwise
from pathlib import Path
from typing import Any

import pytest

from pysilver.spec import SpecError, parse_view
from pysilver.spec.loader import load_view
from pysilver.spec.models import TYPE_ROLES
from pysilver.spec.typescale import TYPE_SCALE


def view(scale: dict | None, style: dict):
    payload: dict = {"root": {"name": "t", "widget": "Text", "text": "x", "style": style}}
    if scale is not None:
        payload["type_scale"] = scale
    return parse_view(payload)


# ------------------------------------------------------------ vocabulary


def test_there_are_fifteen_roles() -> None:
    """M3: "15 baseline" styles, "from Display Large to Label Small"."""
    assert len(TYPE_ROLES) == 15
    assert TYPE_ROLES[0] == "display-large"
    assert TYPE_ROLES[-1] == "label-small"


def test_every_group_has_three_steps() -> None:
    for group in ("display", "headline", "title", "body", "label"):
        steps = [r for r in TYPE_ROLES if r.startswith(f"{group}-")]
        assert len(steps) == 3, group


def test_a_name_outside_the_vocabulary_is_rejected() -> None:
    with pytest.raises(SpecError):
        view({"title-large": 22}, {"text_style": "title-enormous"})


# ------------------------------------------------------------ resolution


def test_a_role_resolves_to_a_font_size() -> None:
    parsed = view({"title-large": 22}, {"text_style": "title-large"})
    assert parsed.root.style.font_size == 22.0


def test_resolution_happens_at_load() -> None:
    """So every widget downstream keeps reading a plain float, and a role
    costs nothing per frame."""
    parsed = view({"body-medium": 14}, {"text_style": "body-medium"})
    assert isinstance(parsed.root.style.font_size, float)


def test_a_role_beats_an_explicit_size() -> None:
    """Naming a role is the more specific statement of intent."""
    parsed = view({"title-large": 22}, {"text_style": "title-large", "font_size": 99})
    assert parsed.root.style.font_size == 22.0


def test_text_without_a_role_is_untouched() -> None:
    parsed = view({"title-large": 22}, {"font_size": 17})
    assert parsed.root.style.font_size == 17.0
    assert parsed.root.style.text_style is None


def test_roles_resolve_inside_nested_nodes_and_overlays() -> None:
    parsed = parse_view(
        {
            "type_scale": {"title-large": 22},
            "root": {
                "name": "root",
                "widget": "Vertical",
                "children": [
                    {"name": "deep", "widget": "Text", "style": {"text_style": "title-large"}}
                ],
            },
            "overlays": [
                {
                    "name": "d",
                    "widget": "Dialog",
                    "open": "true",
                    "style": {"text_style": "title-large"},
                }
            ],
        }
    )
    assert parsed.root.children[0].style.font_size == 22.0
    assert parsed.overlays[0].style.font_size == 22.0


def test_a_view_with_no_roles_is_not_rewritten() -> None:
    """The common case must not pay for a tree copy."""
    from pysilver.spec.typescale import apply_type_scale

    parsed = parse_view({"name": "t", "widget": "Text", "text": "x"})
    assert apply_type_scale(parsed) is parsed


# --------------------------------------------------------- missing sizes


def test_every_role_resolves_without_a_declared_scale() -> None:
    """The built-in scale covers all fifteen, so a view need declare nothing."""
    for role in TYPE_ROLES:
        parsed = view(None, {"text_style": role})
        assert parsed.root.style.font_size > 0


def test_a_view_overrides_the_built_in_scale_per_role() -> None:
    parsed = parse_view(
        {
            "type_scale": {"title-large": 30},
            "root": {
                "name": "root",
                "widget": "Vertical",
                "children": [
                    {"name": "a", "widget": "Text", "style": {"text_style": "title-large"}},
                    {"name": "b", "widget": "Text", "style": {"text_style": "body-medium"}},
                ],
            },
        }
    )
    assert parsed.root.children[0].style.font_size == 30.0
    assert parsed.root.children[1].style.font_size == TYPE_SCALE["body-medium"].size


# ---------------------------------------------------------------- sharing


def test_a_scale_can_live_in_its_own_file(tmp_path: Path) -> None:
    (tmp_path / "scale.yaml").write_text("title-large: 22\nbody-medium: 14\n")
    (tmp_path / "app.yaml").write_text(
        "type_scale: {source: scale.yaml}\n"
        "root: {name: t, widget: Text, text: x, style: {text_style: title-large}}\n"
    )
    parsed = load_view(tmp_path / "app.yaml")
    assert parsed.root.style.font_size == 22.0


def test_an_included_scale_is_watched_for_reload(tmp_path: Path) -> None:
    (tmp_path / "scale.yaml").write_text("title-large: 22\n")
    (tmp_path / "app.yaml").write_text(
        "type_scale: {source: scale.yaml}\n"
        "root: {name: t, widget: Text, text: x, style: {text_style: title-large}}\n"
    )
    sources: set[Path] = set()
    load_view(tmp_path / "app.yaml", sources=sources)
    assert {p.name for p in sources} == {"app.yaml", "scale.yaml"}


def test_a_scale_file_of_non_numbers_is_rejected(tmp_path: Path) -> None:
    (tmp_path / "scale.yaml").write_text("title-large: enormous\n")
    (tmp_path / "app.yaml").write_text(
        "type_scale: {source: scale.yaml}\nroot: {name: t, widget: Text, text: x}\n"
    )
    with pytest.raises(SpecError, match="maps each role to a number"):
        load_view(tmp_path / "app.yaml")


# ------------------------------------------------------------- provenance


def test_the_scale_has_all_fifteen_roles() -> None:
    assert set(TYPE_SCALE) == set(TYPE_ROLES)


def test_it_agrees_with_every_value_the_reference_library_corroborates() -> None:
    """Four roles appear with a size in `M3-References` independently of the
    token source. If those ever disagree, one of the two is wrong and this
    should say so loudly rather than let it pass."""
    corroborated = {
        "headline-medium": 28.0,  # app bar, expanded medium
        "title-large": 22.0,  # app bar title, small/centre-aligned
        "title-small": 14.0,
        "label-medium": 12.0,
    }
    for role, size in corroborated.items():
        assert TYPE_SCALE[role].size == size, role


def test_it_settles_the_contradiction_in_the_reference_library() -> None:
    """`headline-large` appears in `M3-References` as both 32sp and 36sp, in
    the same file. The token source says 32."""
    assert TYPE_SCALE["headline-large"].size == 32.0


def test_the_scale_descends_within_each_group() -> None:
    for group in ("display", "headline", "title", "body", "label"):
        sizes = [TYPE_SCALE[f"{group}-{s}"].size for s in ("large", "medium", "small")]
        assert sizes == sorted(sizes, reverse=True), group


def test_the_recorded_tokens_are_plausible() -> None:
    """Line height is never smaller than the size it belongs to, and weights
    are real Roboto weights -- a guard against a transcription slip."""
    for role, style in TYPE_SCALE.items():
        assert style.line_height >= style.size, role
        assert style.weight in (400, 500), role


def test_the_example_documents_its_provenance() -> None:
    """`examples/typescale.yaml` is now an override sample, but it must keep
    saying where the built-in figures came from."""
    path = Path(__file__).resolve().parents[1] / "examples/typescale.yaml"
    text = path.read_text()
    assert "material-web" in text
    assert "34.0.21" in text


# ------------------------------------------------------------------ weight


def test_a_role_carries_its_weight() -> None:
    """Roboto ships Regular and Medium, so `title-medium` is genuinely Medium
    rather than emboldened Regular."""
    assert view(None, {"text_style": "title-medium"}).root.style.font_weight == 500
    assert view(None, {"text_style": "body-large"}).root.style.font_weight == 400


def test_an_explicit_weight_beats_the_role() -> None:
    """Naming a role states an intent; writing a weight beside it states a more
    specific one."""
    parsed = view(None, {"text_style": "body-large", "font_weight": 500})
    assert parsed.root.style.font_weight == 500


def test_weight_defaults_to_regular() -> None:
    assert view(None, {"font_size": 20}).root.style.font_weight == 400


def test_the_weights_match_the_recorded_tokens() -> None:
    for role in TYPE_ROLES:
        assert view(None, {"text_style": role}).root.style.font_weight == TYPE_SCALE[role].weight


def test_weight_changes_the_measured_metrics() -> None:
    """A different weight is a different face, not a synthetic thickening --
    which is why layout and paint must pass the same one."""
    from pysilver.widgets.base import measure_text

    regular = measure_text("Sample text", 20.0, weight=400)
    medium = measure_text("Sample text", 20.0, weight=500)
    assert regular.width != medium.width


def test_a_missing_weight_resolves_to_the_nearest_available() -> None:
    """Roboto has no Bold here, so 700 renders as Medium rather than as a
    smeared Regular."""
    from pysilver.text import TextEngine
    from pysilver.text.fontdb import FontRequest

    db = TextEngine().db
    assert db.face_for(FontRequest(weight=700)).weight == 500
    assert db.face_for(FontRequest(weight=400)).weight == 400


def test_components_hold_the_m3_role_their_spec_names() -> None:
    """M3_COMPONENT_SPECS: a common button is `label-large` "(14sp / 20dp line
    height, medium weight)"; a navigation bar's label is `label-medium`; a tab
    is `title-small`. Quoted, not inferred.

    The whole role is held, not a size and a weight side by side, so its three
    numbers cannot reach a widget's measure and its paint separately.
    """
    from pysilver.widgets.base import ButtonElement
    from pysilver.widgets.navigation import LABEL_ROLE, TAB_LABEL_ROLE, TITLE_ROLE

    assert ButtonElement.LABEL_ROLE is TYPE_SCALE["label-large"]
    assert LABEL_ROLE is TYPE_SCALE["label-medium"]
    assert TAB_LABEL_ROLE is TYPE_SCALE["title-small"]
    assert TITLE_ROLE is TYPE_SCALE["title-large"]
    assert (ButtonElement.LABEL_ROLE.weight, ButtonElement.LABEL_ROLE.tracking) == (500, 0.1)


def _paint_once(spec: dict[str, object], width: float, height: float) -> tuple[Any, Any]:
    """Lay out and paint one widget through a single text engine, and return it.

    The engine memoises paragraphs on the *whole* set of parameters -- text,
    size, face, alignment, wrap width, tracking -- so a widget that measured
    with one and painted with another leaves two entries where there should be
    one. That makes the cache a mismatch detector, and it covers every
    parameter at once rather than the one a hand-written assertion remembers.
    """
    from pysilver.layout import Constraints, Offset
    from pysilver.paint import DisplayList
    from pysilver.text import TextEngine
    from pysilver.theme import Palette, Theme
    from pysilver.tree.element import PaintContext
    from pysilver.widgets import build_element

    engine = TextEngine()
    element = build_element(parse_view(spec).root)
    element.set_text_engine(engine)
    element.layout(Constraints(0.0, width, 0.0, height))
    ctx = PaintContext(
        display_list=DisplayList(), palette=Palette(Theme()), text=engine, pixel_ratio=1.0
    )
    element.paint(ctx, Offset(0.0, 0.0))
    return engine, ctx.display_list


@pytest.mark.parametrize(
    ("spec", "label"),
    [
        ({"name": "b", "widget": "Button", "text": "Confirm"}, "Confirm"),
        ({"name": "n", "widget": "NavItem", "icon": "home", "label": "Home"}, "Home"),
        ({"name": "t", "widget": "Tab", "text": "Overview"}, "Overview"),
        ({"name": "s", "widget": "Segment", "text": "Weekly"}, "Weekly"),
        (
            {"name": "x", "widget": "Text", "text": "Body", "style": {"text_style": "body-large"}},
            "Body",
        ),
    ],
)
def test_a_label_is_measured_and_painted_with_one_set_of_metrics(
    spec: dict[str, object], label: str
) -> None:
    """A widget measures and paints its label in separate calls. If they
    disagree on size, face or tracking, the box is sized for one rendering and
    drawn in another -- which clips it. This caught a real bug when weight was
    applied, and tracking is a third chance at the same mistake.

    Only the *metrics* have to match. A `Text` legitimately measures against the
    width it is offered and paints against the narrower box it settled on --
    that is how it shrink-wraps instead of starving its siblings in a Horizontal.
    """
    from pysilver.paint.display_list import Kind

    engine, display_list = _paint_once(spec, 200.0, 80.0)
    assert any(s["flags"][0] == Kind.GLYPH for s in display_list.view), "no label was drawn"
    metrics = {(k[1], k[3], k[5], k[6]) for k in engine._layouts if k[0] == label}
    assert len(metrics) == 1, f"measure and paint disagreed: {metrics}"


def test_a_button_label_carries_its_whole_role_into_the_paint_pass() -> None:
    """The positive case behind the test above: not merely consistent, but
    consistent at the figures `label-large` actually specifies.

    Indexed by name rather than position -- the cache key has grown twice as
    the scale was applied, and `key[-1]` silently moved from tracking to line
    height the second time.
    """
    role = TYPE_SCALE["label-large"]
    engine, _ = _paint_once({"name": "b", "widget": "Button", "text": "Confirm"}, 200.0, 80.0)
    (key,) = [k for k in engine._layouts if k[0] == "Confirm"]
    size, face, tracking, line_height = key[1], key[3], key[5], key[6]
    assert (size, face[1], tracking, line_height) == (14.0, 500, 0.1, 20.0)
    assert (size, face[1], tracking, line_height) == (
        role.size,
        role.weight,
        role.tracking,
        role.line_height,
    )


# --------------------------------------------------------------- tracking


def test_a_role_resolves_its_tracking_into_letter_spacing() -> None:
    parsed = view(None, {"text_style": "body-large"})
    assert parsed.root.style.letter_spacing == TYPE_SCALE["body-large"].tracking == 0.5


def test_most_roles_track_zero() -> None:
    """Worth pinning: tracking is the exception in this scale, not the rule, so
    a change that gave every role a nonzero value would be a mistake."""
    zero = [name for name, style in TYPE_SCALE.items() if style.tracking == 0.0]
    assert len(zero) == 6, "display-medium and -small, all three headlines, title-large"
    assert TYPE_SCALE["display-large"].tracking == -0.25, "the only negative one"
    assert max(s.tracking for s in TYPE_SCALE.values()) == 0.5, "and the widest is half a pixel"


def test_an_explicit_letter_spacing_beats_the_role() -> None:
    parsed = view(None, {"text_style": "body-large", "letter_spacing": 3.0})
    assert parsed.root.style.letter_spacing == 3.0


def test_a_resized_role_keeps_its_own_tracking() -> None:
    """`type_scale:` overrides a size. Tracking is a separate token, and
    resizing a role says nothing about it."""
    parsed = view({"body-large": 20}, {"text_style": "body-large"})
    assert parsed.root.style.font_size == 20.0
    assert parsed.root.style.letter_spacing == 0.5


def test_tracking_widens_text_by_one_step_per_cluster() -> None:
    """Per *cluster*, not per glyph: "fi" shapes to a single ligature glyph for
    two characters and must not be pulled apart from the inside."""
    from pysilver.text import TextEngine

    engine = TextEngine()
    text = "Hamburgefonstiv fi"
    plain = engine.layout(text, px=16.0)
    tracked = engine.layout(text, px=16.0, tracking=2.0)
    assert len(plain.placements()) == 17, "expected the fi ligature"
    assert tracked.size.width - plain.size.width == pytest.approx(2.0 * 17)


def test_negative_tracking_narrows_text() -> None:
    from pysilver.text import TextEngine

    engine = TextEngine()
    assert (
        engine.layout("Display", px=57.0, tracking=-0.25).size.width
        < engine.layout("Display", px=57.0).size.width
    )


def test_the_caret_follows_tracked_glyphs() -> None:
    """Selection walks advances itself. If it read them without tracking, a
    click would land on a different character than the one under the cursor --
    which is why both go through `ShapedRun.advances_px`.
    """
    from pysilver.text import TextEngine
    from pysilver.text.selection import index_at

    para = TextEngine().layout("Selection", px=16.0, tracking=4.0)
    assert index_at(para, para.size.width, 0.0) == len("Selection")
    for want, place in enumerate(para.placements()):
        assert index_at(para, place.x + 0.01, 0.0) == want


def test_shaping_stays_size_and_tracking_independent() -> None:
    """Tracking is applied in pixels at layout time, so one shaped run still
    serves every size and every spacing the same string is drawn at."""
    from pysilver.text import TextEngine

    engine = TextEngine()
    for tracking in (0.0, 0.5, 2.0):
        engine.layout("Shared", px=16.0, tracking=tracking)
    _, misses = engine.shaper.stats
    assert misses == 1, "tracking re-shaped the run"


# ------------------------------------------------------------ line height


def test_a_role_resolves_its_line_height() -> None:
    parsed = view(None, {"text_style": "body-large"})
    assert parsed.root.style.line_height == TYPE_SCALE["body-large"].line_height == 24.0


def test_an_explicit_line_height_beats_the_role() -> None:
    parsed = view(None, {"text_style": "body-large", "line_height": 30.0})
    assert parsed.root.style.line_height == 30.0


def test_unset_line_height_keeps_the_fonts_own() -> None:
    """The default is None, not a number: most text is not part of a scale, and
    a framework-wide figure would be a worse guess than the face's metrics."""
    parsed = view(None, {"font_size": 14})
    assert parsed.root.style.line_height is None


def test_line_height_sets_the_measured_height() -> None:
    from pysilver.text import TextEngine

    engine = TextEngine()
    assert engine.layout("One line", px=14.0, line_height=40.0).size.height == 40.0
    assert engine.layout("", px=14.0, line_height=40.0).size.height == 40.0, "empty text too"


def test_leading_is_split_evenly_so_centred_text_does_not_move() -> None:
    """The reason this is half-leading and not space added below: a button's
    label measures 20dp tall instead of 17, and stays exactly where it was.
    """
    from pysilver.text import TextEngine

    role = TYPE_SCALE["label-large"]
    engine = TextEngine()
    scaled = engine.layout("Confirm", px=role.size, line_height=role.line_height)
    natural = engine.layout("Confirm", px=role.size)
    assert scaled.size.height == 20.0 and natural.size.height == 17.0
    centred = [(40.0 - p.size.height) / 2 + p.lines[0].baseline for p in (scaled, natural)]
    assert centred[0] == centred[1] == 24.5


def test_a_line_height_below_the_fonts_own_is_allowed() -> None:
    """It occurs in the real scale -- Roboto wants 67px at display-large where
    M3 asks for 64 -- so negative leading has to close lines up rather than
    crop them."""
    from pysilver.text import TextEngine
    from pysilver.text.fontdb import FontRequest

    engine = TextEngine()
    natural = engine.db.face_for(FontRequest()).metrics(57.0).line_height
    assert TYPE_SCALE["display-large"].line_height < natural
    para = engine.layout("Ag", px=57.0, line_height=TYPE_SCALE["display-large"].line_height)
    assert para.size.height == 64.0
    assert para.lines[0].baseline < natural, "the baseline rose with the line"


def test_line_height_stacks_every_line() -> None:
    from pysilver.text import TextEngine

    para = TextEngine().layout(
        "wrap this text over several lines please", px=14.0, max_width=80.0, line_height=20.0
    )
    assert len(para.lines) > 1
    assert para.size.height == 20.0 * len(para.lines)
    baselines = [line.baseline for line in para.lines]
    assert all(b - a == 20.0 for a, b in pairwise(baselines))


def test_every_role_now_resolves_all_four_tokens() -> None:
    """The scale is fully applied. If a fifth token is ever added to
    `TypeStyle`, this is the test that should fail."""
    from dataclasses import fields

    assert [f.name for f in fields(TYPE_SCALE["body-large"])] == [
        "size",
        "line_height",
        "weight",
        "tracking",
    ]
    parsed = view(None, {"text_style": "title-small"})
    role = TYPE_SCALE["title-small"]
    assert (
        parsed.root.style.font_size,
        parsed.root.style.line_height,
        parsed.root.style.font_weight,
        parsed.root.style.letter_spacing,
    ) == (role.size, role.line_height, role.weight, role.tracking)
