"""M3 type-scale roles, and the figures behind them.

The sizes here are **sourced**, and the sourcing is worth recording because it
was not straightforward.

The spec page at <https://m3.material.io/styles/typography/type-scale-tokens>
serves a JavaScript shell with no body content at all, which is why the token
table in `M3-References` scraped empty -- not a scraping mistake, just how that
page is delivered. The values instead come from Google's own autogenerated
token source in the Material Web Components repository:

    tokens/versions/latest/sass/_md-sys-typescale.scss
    Design system: Google Material 3, Version: 34.0.21

Two things make that trustworthy rather than merely convenient. It is
autogenerated from the same token pipeline the spec page renders from, and it
**agrees with every value the reference library corroborated independently** --
headline-medium 28, title-large 22, title-small 14, label-medium 12. It also
settles the one contradiction in the library, where `headline-large` appeared
as both 32sp and 36sp in the same file: it is **32**.

Sizes are converted from the source's `rem` at the CSS default of 16px/rem.

**All four tokens are applied.** A role resolves to `font_size`,
`font_weight`, `letter_spacing` and `line_height`. Roboto ships the Regular and
Medium faces the scale asks for, so `title-medium` is genuinely Medium rather
than emboldened Regular.

Tracking and line height are **absolute** figures in logical px, not multiples
of the size -- that is how the source states them (both in rem, converted at
the same 16px/rem as the sizes), and it is why a role's figures are only right
at that role's size. Nine of the fifteen roles track something.

A role's line height is not always taller than the font's own: Roboto wants 67px
at `display-large`, where M3 asks for 64. Both directions work, because the
difference is split evenly above and below the glyphs rather than added below
them.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Final

from .models import StyleSpec, ViewSpec, WidgetSpec

__all__ = ["TYPE_SCALE", "TypeScaleError", "TypeStyle", "apply_type_scale"]


@dataclass(frozen=True, slots=True)
class TypeStyle:
    """One role's four tokens, all of which a `text_style:` resolves."""

    size: float
    line_height: float
    weight: int
    tracking: float


#: M3's 15 baseline type styles. Source and provenance in the module docstring.
TYPE_SCALE: Final[dict[str, TypeStyle]] = {
    "display-large": TypeStyle(57.0, 64.0, 400, -0.25),
    "display-medium": TypeStyle(45.0, 52.0, 400, 0.0),
    "display-small": TypeStyle(36.0, 44.0, 400, 0.0),
    "headline-large": TypeStyle(32.0, 40.0, 400, 0.0),
    "headline-medium": TypeStyle(28.0, 36.0, 400, 0.0),
    "headline-small": TypeStyle(24.0, 32.0, 400, 0.0),
    "title-large": TypeStyle(22.0, 28.0, 400, 0.0),
    "title-medium": TypeStyle(16.0, 24.0, 500, 0.15),
    "title-small": TypeStyle(14.0, 20.0, 500, 0.1),
    "body-large": TypeStyle(16.0, 24.0, 400, 0.5),
    "body-medium": TypeStyle(14.0, 20.0, 400, 0.25),
    "body-small": TypeStyle(12.0, 16.0, 400, 0.4),
    "label-large": TypeStyle(14.0, 20.0, 500, 0.1),
    "label-medium": TypeStyle(12.0, 16.0, 500, 0.5),
    "label-small": TypeStyle(11.0, 16.0, 500, 0.5),
}


class TypeScaleError(ValueError):
    """A `text_style:` role that the view's `type_scale:` does not define."""


def _resolve(node: WidgetSpec, scale: dict[str, float]) -> WidgetSpec:
    children = tuple(_resolve(child, scale) for child in node.children)
    role = node.style.text_style
    style: StyleSpec | None = None
    if role is not None:
        if role not in scale:
            raise TypeScaleError(
                f"{node.id}: text_style {role!r} has no size. It is not in this "
                f"view's `type_scale:` and not one of M3's 15 baseline roles."
            )
        fields: dict[str, Any] = {
            name: getattr(node.style, name) for name in node.style.model_fields_set
        }
        fields["font_size"] = float(scale[role])
        # An explicit `font_weight:` or `letter_spacing:` on the node wins:
        # naming a role states the intent, but writing either beside it states
        # a more specific one.
        #
        # A view's `type_scale:` overrides only the *size*, so a resized role
        # keeps its own weight and tracking -- they are separate tokens, and
        # resizing a role is not a statement about either.
        known = TYPE_SCALE[role]
        if "font_weight" not in node.style.model_fields_set:
            fields["font_weight"] = known.weight
        if "letter_spacing" not in node.style.model_fields_set:
            fields["letter_spacing"] = known.tracking
        if "line_height" not in node.style.model_fields_set:
            fields["line_height"] = known.line_height
        style = StyleSpec(**fields)

    if style is None and all(a is b for a, b in zip(children, node.children, strict=True)):
        return node
    update: dict[str, Any] = {"children": children}
    if style is not None:
        update["style"] = style
    return node.model_copy(update=update)


def apply_type_scale(view: ViewSpec) -> ViewSpec:
    """Resolve every `text_style:` to a concrete size, weight and tracking.

    A no-op when no node names a role, so the common case pays nothing -- not
    even a tree walk's worth of copying.
    """
    # The built-in scale, with a view's own entries overriding it per role.
    scale: dict[str, float] = {name: style.size for name, style in TYPE_SCALE.items()}
    scale.update({str(k): float(v) for k, v in view.type_scale.items()})
    root = _resolve(view.root, scale)
    overlays = tuple(_resolve(o, scale) for o in view.overlays)
    if root is view.root and all(a is b for a, b in zip(overlays, view.overlays, strict=True)):
        return view
    return view.model_copy(update={"root": root, "overlays": overlays})
